CREATE TABLE bs_users (
   id    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   username VARCHAR2(100) NOT NULL UNIQUE,
   senha_hash    VARCHAR2(255) NOT NULL,
   role_name  VARCHAR2(50) NOT NULL
);